apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ppop5hgfm-python 
  janus-idp.io/tekton: ppop5hgfm-python
  backstage.io/kubernetes-id: ppop5hgfm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppop5hgfm-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml