apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ppop5hgfm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ppop5hgfm-python 
  name: ppop5hgfm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ppop5hgfm-python 
